api:
  provider: azure_openai
  model: gpt-4o-mini
  temperature: 0
  timeout: 30
  retries: 2

paths:
  dataset: data/annotations.csv
  prompt: prompts/vision_only_6.txt

evaluation:
  max_samples: 20   # ex: 50 pour debug
  allowed_types:
    - 1A
    - 1B
    - 1C
    - 2A
    - 2B
    - 2C
    - 3A
    - 3B
    - 3C
    - 4A
    - 4B
    - 4C
    - Unknown
